spring.application.name=springia

spring.datasource.url=jdbc:mysql://localhost:3306/instituto?serverTimezone=UTC

# Tus credenciales de MySQL
spring.datasource.username=root
spring.datasource.password=root

# Configuración de Hibernate (JPA)
# 'update' crea las tablas automáticamente si no existen
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

spring.ai.google.genai.api-key=AIzaSyA95M-o_cS9LO-z6zv4uBnBAAh4KP1qMvo
spring.ai.google.genai.chat.options.model=gemini-flash-latest